### ISSUE TITLE
R41 of x16emu is out

### ISSUE THREAD

**Issue by mobluse** [popey/x16emu-snap#6]
R41 of x16emu is out, and that was preceded with prereleases, so it's probably a more stable release than R39. I would like an upgrade to R41 for the summer.

**Comment by popey** [comment]
Hi @mobluse - x16-emu snap has been failing to build recently. During the build:
`kernal/drivers/x16/ps2kbd.s:6: Error: Cannot open include file 'longbranch.mac': No such file or directory`
I looked at a few cc65 issues around this, fiddled with PREFIX and/or DESTDIR which didn't succeed. I tried dropping the mac files in common under where the cc65 binary is located, but that wasn't found. 

Is there a definitive place I can drop the .mac files where they may be found by cc65?

**Comment by mobluse** [comment]
On my system Raspbian GNU/Linux 10 (buster), which is similar to Debian, longbranch.mac is here:
/usr/share/cc65/asminc/longbranch.mac  
I believe I only installed cc65 2.17-1 from the distribution and it worked out of the box; maybe you use a newer version.
I include my Makefile which is just slightly hacked from the original. I have to log in three times over ssh during the build with `make package_linux`.
[Makefile.txt](https://github.com/popey/x16emu-snap/files/8810453/Makefile.txt)

**Comment by popey** [comment]
Thanks for the help. I was building cc65 from source. By using the version in the repo, x16emu builds now, however it fails to launch with alsa errors. Interestingly previous releases (r39) didn't have this problem. It's certainly possible to add alsa support to x16emu, which I'll take a look at. Confinement in snap makes alsa a pain, which requires some additional nonsense :)

**Comment by mobluse** [comment]
ALSA is not necessary for me since December 2020 I believe since Raspbian Buster uses PulseAudio:
https://www.raspberrypi.com/news/new-raspberry-pi-os-release-december-2020/

**Comment by mobluse** [comment]
I installed R41 now using `sudo snap install x16emu --edge`. I can start it if I use `x16emu -sound none`, but then I get a message in the terminal each 5 seconds:
`ALSA lib conf.c:4120:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf`  

If I try to start it with just `x16emu` I doesn't start, but gives these messages:
```
ALSA lib conf.c:4120:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib conf.c:4120:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
SDL_OpenAudioDevice failed: ALSA: Couldn't open audio device: No such file or directory
```
```
ls -l /usr/share/alsa/alsa.conf
-rw-r--r-- 1 root root 9594 Nov  1  2021 /usr/share/alsa/alsa.conf

```
In my own compiled version I don't have these problems and sound works, but it is a bit chopped, but it has been like this from the start.

**Comment by mobluse** [comment]
For i386:
latest/edge	e568d01	5 April 2022  
I.e. R41 doesn't exist for i386, but I have one EeePC 900 computer that run Lubuntu.
```
           `-/+oyyhhhhyyo+/-`              pi@EeePC900 
        ./shhhhhhhhhhhhhhhhhhs/.           ----------- 
     `:shhhhhhhhhhhhhhhhhhhhhhhhs:`        OS: Ubuntu 18.04.6 LTS i686 
    :yhhhhhhhhhhhhhhhs++yhhhhhhhhhy:       Host: 900 0802 
  `ohhhhhhhhhhhhhs+:. .yhhhhhhhhhhhho`     Kernel: 4.15.0-180-generic 
 `shhhhhhhhhhy+:`     /yhhhhhhhhhhhhhs`    Uptime: 24 mins 
 shhhhhhhhy+.          .ohhhhhhhhhhhhhs    Packages: 1751 
:hhhhhhy/.               /hhhhhhhhhhhhh:   Shell: bash 4.4.20 
shhhy/.                   :hhhhhhhhhhhhs   Terminal: /dev/pts/0 
hy+.   `        `+yhs/`    +hhhhhhhhhhhh   CPU: Intel Celeron M 900MHz (1) @ 900MHz 
-.:/oshy-  `   :yhhhhhy/    shhhhhhhhhhh   GPU: Intel Integrated Graphics 
shhhhhy-`/s. .shhhhhhhhho`  .hhhhhhhhhhs   Memory: 219MiB / 2003MiB 
:hhhho`:ys` /yhhhhhhhhhhhs`  +hhhhhhhhh: 
 shh/.sh+ `ohhhhhhhhhhhhhhs` .hhhhhhhhs                            
 `o-+hh: :yhhhhhhhhhhhhhhhho  ohhhhhhs` 
   +hy-`ohhhhhhhhhhhhhhhhhhh+ -hhhhho` 
    :.-yhhhhhhhhhhhhhhhhhhhhh: yhhy: 
      :shhhhhhhhhhhhhhhhhhhhhy`+s:` 
        .+shhhhhhhhhhhhhhhhhhs:` 
           `-/+oyyhhhhyys+/-
```

**Comment by popey** [comment]
Ok, I've implemented the alsa stuff in the snap, so if you refresh the snap from the edge channel, and then `snap connect x16emu:alsa` it should run fine. I have [requested](https://forum.snapcraft.io/t/alsa-for-x16emu/30326) that the snap has the alsa interface auto-connected so users won't need to do that in future. Once that's done, I'll release the new build to the stable channel.

**Comment by mobluse** [comment]
It works with sound now in Raspbian GNU/Linux 10 (buster) armhf on Raspberry Pi 4 Model B Rev 1.4 after refresh and `snap connect x16emu:alsa`.

**Comment by popey** [comment]
The snap has now had alsa interface approved, and auto connects on install. r41 tested and now published in the stable channel. Thanks again @mobluse for the issue and feedback.

**Comment by mobluse** [comment]
R41 doesn't exist for architecture i386; only R39. 

Now there is also R42, but that is in a different repository https://github.com/X16Community/x16-emulator and I don't know how official it is yet. R42 was announced on the official forum site: https://cx16forum.com/forum/viewtopic.php?t=6399 that is linked from https://www.commanderx16.com/. I believe there will be an R43 soon that will correct some bugs.
